### ISSUE TITLE
Discretization step seems to be different from the paper

### ISSUE THREAD

**Issue by ajtejankar** [alxndrTL/mamba.py#10]
Hi,

Firstly, thanks for making this repo. I found it very useful in understanding the scan algorithm. However, discretization in this repo seems to be different from the Eq 4 of the paper. Do you have any comments on this? Also, I wonder why the original paper needs the discretization step in the first place since it is possible to make the discrete versions of A and B conditioned on the input directly. I imagine that it must have something to do with the initialization, but I am not sure.

https://github.com/alxndrTL/mamba.py/blob/b9f315dbadd9576083facc425fa5b05619d89e07/mamba.py#L248
<img width="1491" alt="image" src="https://github.com/alxndrTL/mamba.py/assets/3609566/9ffce291-445e-4c37-8431-6f4a27df323e">

**Comment by ajtejankar** [comment]
Hi @alxndrTL ,

Thanks a lot. That's very helpful. I think the authors should clarify this somewhere, since some people seem to be confused by it.

**Comment by llmexperiment** [comment]
> Hi @alxndrTL ,
> 
> Thanks a lot. That's very helpful. I think the authors should clarify this somewhere, since some people seem to be confused by it.

That is also what I confused. Thanks for clarifying this.
