### ISSUE TITLE
Mamba profiling_mamba.py script 

### ISSUE THREAD

**Issue by llmexperiment** [alxndrTL/mamba.py#13]
Hi,

Thanks for the repo! This is really useful! 

1) I can not run the [profiling_mamba.py](https://github.com/alxndrTL/mamba.py/blob/main/tests/profiling_mamba.py)
It is missing these args "unfolded=True, rev=True, version='3'" in MambaConfig class.

**Comment by alxndrTL** [comment]
Thank you!
Yes, this script was written with a dev version of the repo, it has been update now ;)
(just had to remove the `unfolded, rev, version` arguments)

**Comment by llmexperiment** [comment]
Thanks Alex! 

One more thing, I noticed that  

https://github.com/alxndrTL/mamba.py/blob/main/tests/profiling_pscan.py is missing following two files? 

from pscan_unfolded import pscan as pscan_unfolded
from pscan_unfolded_rev import pscan as pscan_unfolded_rev
