### ISSUE TITLE
Support batch size > 1?

### ISSUE THREAD

**Issue by yjdy** [alxndrTL/mamba.py#15]
Support for  batch size > 1, how is the progress of the work?

**Comment by alxndrTL** [comment]
Hello! This is done (for the PyTorch version).

Here is the behavior :
you can now specify a `batch_size` in the `generate` function :

`
outputs = model.generate(tokenizer, "Mamba is a type of", batch_size=16)
`

this will sample in this case `16` different completions from the same prompt:

![Capture d’écran du 2024-03-30 11-26-46](https://github.com/alxndrTL/mamba.py/assets/22843596/301a80ff-bd30-4878-9b8c-be5d69683113)

I hope this helps you
