### ISSUE TITLE
Integration to `transformers`

### ISSUE THREAD

**Issue by ArthurZucker** [alxndrTL/mamba.py#19]
Hey! I ported `mamba` to `transformers` and think your approach to replace the naive scan would be great there! 
Would you like to open a PR? 🤗 (to https://github.com/huggingface/transformers)

**Comment by alxndrTL** [comment]
Hello, thank you for reaching me out, sure I will start working on it !

**Comment by alxndrTL** [comment]
Hello @ArthurZucker, I just posted the [PR](https://github.com/huggingface/transformers/pull/30139) to `transformers` :)

**Comment by ArthurZucker** [comment]
Thanks! will check it out!
