### ISSUE TITLE
A fresh can't start the model

### ISSUE THREAD

**Issue by Luchen-077** [alxndrTL/mamba.py#20]
I'm sorry that I'm a fresh, so I can't get the model running smoothly.
When I start the 'example_llm.ipynb', I get the error like this
![图片](https://github.com/alxndrTL/mamba.py/assets/134530542/43470f92-d93b-40d0-887b-2c7727efbc14)
and then I tried to copy the same code to .py file, I get the error like 
![图片](https://github.com/alxndrTL/mamba.py/assets/134530542/988bb7cb-133e-4c28-84ff-4493589bedf0)

the same question had been met in 'mamba-minimal', I don't know how to solve it.Bless for help, thank you!

**Comment by alxndrTL** [comment]
Hello, it seems the error you're seeing in the example_llm.ipynb is due to `torch.load` not recognizing the `mmap` argument that is given to it.
What is your torch version ?

**Comment by Luchen-077** [comment]
pytorch version 1.13.0
and I had just deleted the sentence 'mmap=True', then my code succeed running, may my action cause some severe problem?

**Comment by alxndrTL** [comment]
If it runs then you're good, the `mmap` argument decides how the file loaded with `torch.load` (in this case, the model weights) is loaded. It can be directly loaded in RAM in one go (if `mmap=False`) or loaded in RAM in chunks, whenever a chunk is necessary for computation. If it works, just leave it as is. (but you may consider upgrading your `torch` in the future)
