### ISSUE TITLE
Working on AMD ROCm Platform

### ISSUE THREAD

**Issue by supersonictw** [alxndrTL/mamba.py#22]
Thank you.

[state-spaces/mamba](https://github.com/state-spaces/mamba) is not working due to CUDA required.
But this one you created is working successfully. Thank you!!! :smile: 

![Screenshot](https://github.com/alxndrTL/mamba.py/assets/13705584/71d0807b-fda1-4c99-9177-601b6e0c80ce)

**Comment by alxndrTL** [comment]
Hello, it's a pleasure to help!
