### ISSUE TITLE
Error in the Mamba Block forward function?

### ISSUE THREAD

**Issue by erlebach** [alxndrTL/mamba.py#41]
I am going through the code line by line and adding additional comments with shape information.  Inside the MambaBlock's forward function, duplicated below: 
```
    def forward(self, x):
        # input x : (B, L, D)
        # return : (B, L, D)

        _, L, _ = x.shape

        # in_proj: D -->  2*ED (two or three branches)
        xz = self.in_proj(x) # (B, L, 2*ED)
        x, z = xz.chunk(2, dim=-1) # (B, L, ED), (B, L, ED)

        # x branch
        # rearrange(x, "... ED L -> ... L ED")
        x = x.transpose(1, 2) # (B, ED, L)
        # What is the point of convolution?
        x = self.conv1d(x)[:, :, :L] # depthwise convolution over time, with a short filter
        # rearrange(x, "... L ED -> ... ED L")
        x = x.transpose(1, 2) # (B, L, ED)

        #  x --> conv1d --> silu --> ssm  --> y ---> output (y*z) --> (B, L, ED)
        #                             ^          /
        #  z -------------> silu ---- |---------/

        x = F.silu(x)
        y = self.ssm(x, z)   # (B, L, ED), (B, L, ED) --> (B, L, ED)
        print(f"Return from self.ssm, {y.shape=}")

        # GE: why the early exit if using CUDA?
        if self.config.use_cuda:     ######<<<<<<<<
            output = self.out_proj(y) # (B, L, D)
            return output

        # z branch
        z = F.silu(z)   #  (B, L, ED)

        # Why multiply y * z?
        output = y * z
        #              ED -> D
        output = self.out_proj(output) # (B, L, D)
        return output  # (B, L, D)
```
there is the conditional: 
```         if self.config.use_cuda:     ```
Depending on whether cuda is used or not, the output of the forward() method is different. If cuda is not used, there an additional `F.silu` applied to `z` followed by `output=y*z`.

If this is not an error, could you please explain the reason for this apparent discrepancy? Thanks.

    Gordon

**Comment by alxndrTL** [comment]
Hello,

This is intented, if you look at the `forward` function of the `MambaBlock`, if `use_cuda=True`, the function `selective_scan_cuda` is called. It does the same job as the ones implemented in torch (`selective_scan` and `selective_scan_seq`) but, as the comment points out, it also does the softplus, bias and y * silu(z) operations (these ops are fused)

https://github.com/alxndrTL/mamba.py/blob/3cdbd5ee9c23794c45e3112e38b6cff60f3692cb/mambapy/mamba.py#L242:L252.

Hope thi helps.

**Comment by alxndrTL** [comment]
(made a commit https://github.com/alxndrTL/mamba.py/commit/1da4200753fabcc37bfa99afb40ace8c30255074)

**Comment by erlebach** [comment]
I see it now! Thanks for the comment. The AI did mention fusion as a possibility, but I couldn't see it.
