### ISSUE TITLE
Parallel pscan

### ISSUE THREAD

**Issue by erlebach** [alxndrTL/mamba.py#42]
I am looking at the file pscan.py, and see: 
```
class PScan(torch.autograd.Function):
    @staticmethod
    def pscan(A, X):
        # A : (B, D, L, N)
        # X : (B, D, L, N)

        # modifies X in place by doing a parallel scan.
        # more formally, X will be populated by these values :
        # H[t] = A[t] * H[t-1] + X[t] with H[0] = 0
        # which are computed in parallel (2*log2(T) sequential steps (ideally), instead of T sequential steps)

        # only supports L that is a power of two (mainly for a clearer code)

        B, D, L, _ = A.size()
        num_steps = int(math.log2(L))

        # up sweep (last 2 steps unfolded)
        Aa = A
        Xa = X
        for _ in range(num_steps-2):
            T = Xa.size(2)
            Aa = Aa.view(B, D, T//2, 2, -1)
            Xa = Xa.view(B, D, T//2, 2, -1)

            Xa[:, :, :, 1].add_(Aa[:, :, :, 1].mul(Xa[:, :, :, 0]))
            Aa[:, :, :, 1].mul_(Aa[:, :, :, 0])

            Aa = Aa[:, :, :, 1]
            Xa = Xa[:, :, :, 1]
          ...
 ```
 This function is not using MLX. Where exactly is the parallelism? I must not understand because the number of operations is O(T) and is fully sequential.  I am sure I am missing something simple. 
 
     Gordon

**Comment by alxndrTL** [comment]
First, this is the torch version of the pscan, not MLX (although the pscan is also implemented in MLX).

The parallelism is done across the time dimension (third dimension of the inputs `A` and `X`). The number of steps is O(logT). For example, when we do `Xa[:, :, :, 1].add_(Aa[:, :, :, 1].mul(Xa[:, :, :, 0]))`, this does multiple operations in parallel across the time dimension.
I have quite  detailed the algorithm in the `docs` folder of the repo (not completely finished but a good bit has been written already). Feel free to check it.

**Comment by erlebach** [comment]
Thank you for your reponse. I will check the docs. Great work, @alxndrTL !
