### ISSUE TITLE
Partial batches in Mamba_lm

### ISSUE THREAD

**Issue by erlebach** [alxndrTL/mamba.py#43]
I found an unnecessary check in the In the  `get_data()` function of `mamba_lm`, you clearly ensure that there are no partial batches. 

In the training loop (below the `get_batch()` function), you check whether there are partial batches, and skip in case there is. This check is unnecessary. 

Here is the relevant code. First `get_batch()`: 
```
    def get_batch(
        data: Float[T, " B Examples"], seq_len: int, idx: int
    ) -> tuple[Float[T, "B SeqLen"], Float[T, "B SeqLen"]]:
        """Retrieve a single batch"""

        src = data[:, idx : idx + seq_len]  # noqa: E203
        target = data[:, idx + 1 : idx + seq_len + 1]  # noqa: E203
        return src, target
```
where the batch size is always the same. There are no partial batches. Below is the extraneous check: 
```
            # If the batch is not complete - skip
            ###  The batch is always complete
            if logits.view(-1, logits.size(-1)).shape[0] != output.view(-1).shape[0]:   # <<<< UNNECESSARY
                print("skip")
            else:
                loss = F.cross_entropy(logits.view(-1, logits.size(-1)), output)
                avg_loss += loss.item()

                optim.zero_grad()
                loss.backward()
```

**Comment by alxndrTL** [comment]
Indeed it seems that this check is useless as it compares two number that will always be equal, even if the batch is partial.
I will make the changes. (note that I didn't write this code)
