### ISSUE TITLE
No module named 'mambapy.mamba_lm'

### ISSUE THREAD

**Issue by ooooma** [alxndrTL/mamba.py#54]
on the example trainMamba.py i find it use from mambapy.mamba_lm import MambaLM, MambaLMConfig,
but i can't find mamba_lm in mambapy
![Uploading 截屏2024-09-05 14.40.21.png…]()

**Comment by alxndrTL** [comment]
Hello, have you installed `mambapy` with `pip install mambapy` ?
This was the intended use in this script. You can also choose not to install `mambapy` and have it locally by copying the `mambapy` folder
