### ISSUE TITLE
Bibtex

### ISSUE THREAD

**Issue by JulienSiems** [alxndrTL/mamba.py#55]
Hey Alexandre, 

Thank you so much for your work in this repo! We are using it right now for our research because it allows us to change different components in Mamba much more flexibly than in the CUDA or now triton code for Mamba 2.

Could you put a bibtex in the readme so that we can give you proper attribution?

Best, 
Julien

**Comment by alxndrTL** [comment]
Hello Julien,

It's done, right at the end of the readme.

Also, thank you for taking the time to do it! This is a great honor for me and I'm pleased my work helps.

Best,
Alexandre

**Comment by alxndrTL** [comment]
Congrats for the paper!
Wow, I wish I had more time to try out all the things that got published recently.
Wishing you the best of luck for the acceptance!
