### ISSUE TITLE
MLX inference error with BFloat16

### ISSUE THREAD

**Issue by beebopkim** [alxndrTL/mamba.py#6]
from commit hash 6a49341eb6d0b9f06eb490dc285abe69e3bef5fc:

What I have done was executing generate.py for a mamba fine-tuned model - ```kuotient/mamba-ko-2.8b```, and below error was happened. How can I deal with this error?

```
(venv_mamba_py) ******@Mac-Studio-2022-01 scripts % python generate.py --prompt="Mamba is a type of" --hf_model_name="kuotient/mamba-ko-2.8b" --n_tokens=100

Traceback (most recent call last):
  File "/Users/******/test/mamba.py/mlx/scripts/generate.py", line 31, in <module>
    model = MambaLM.from_pretrained(args.hf_model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/******/test/mamba.py/mlx/mamba_lm_mlx.py", line 150, in from_pretrained
    mlx_state_dict = map_mambassm_torch_to_mlx(state_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/******/test/mamba.py/mlx/utils.py", line 53, in map_mambassm_torch_to_mlx
    return map_mambapy_torch_to_mlx(new_state_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/******/test/mamba.py/mlx/utils.py", line 37, in map_mambapy_torch_to_mlx
    new_state_dict[key] = value.numpy()
                          ^^^^^^^^^^^^^
TypeError: Got unsupported ScalarType BFloat16
```

My environments are:
- M1 Max Mac Studio 2022
  - 10 CPUs, 32 GPUs, with 64GB of memory(up to 48GB of VRAM)
- macOS Sonoma 14.2.1
- Python 3.11.7 from homebrew
  - torch 2.3.0.dev20240126 from https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - mlx 0.0.11
  - transformers 4.37.1

**Comment by alxndrTL** [comment]
Hello, it seems the problem arises during the conversion of the weights (from torch to MLX) : the weights are converted (temporary) to numpy. (must be, cf [MLX docs](https://ml-explore.github.io/mlx/build/html/usage/numpy.html))
However, numpy doesn't support `bfloat16`, so it throws an error.

To avoid this, we will work with `float16` in numpy.


First, in ```utils.py```, in the ```‎map_mambapy_torch_to_mlx``` function, replace this line :

```
new_state_dict[key] = value.numpy()
```

by this line :

```
new_state_dict[key] = value.half().numpy()
```

This should save the `.npz` weight file in `float16`.
When loading the file in the MLX Mamba model, it should also load it as `float16`.

For inference with `bfloat16`, MLX doesn't seem to support it yet : https://ml-explore.github.io/mlx/build/html/python/data_types.html?highlight=types

Hope this helps!

**Comment by alxndrTL** [comment]
Thanks for the details.
I see that in the `example_mamba_llm.py`, you use the same tokenizer as the regular Mamba models `EleutherAI/gpt-neox-20b`. Are you sure it's the tokenizer you want with `kuotient/mamba-ko-2.8b` ?

**Comment by alxndrTL** [comment]
Thanks for the details.
The output you're seeing is weird, have you tried prompting the model with korean like you did in `example_mamba_llm.py` ?
I noticed that you called `generate.py` with the english prompt "Mamba is a type of"...

If this doesn't still work and you keep seeing these characters : � , maybe its due to the printing ? Or some UTF-8 stuff ?
In `generate.py`, I simply wrote : 

```
print(token, end='', flush=True)
```

but maybe this doesn't support printing korean characters ?

**Comment by beebopkim** [comment]
As I investigated, I found that the only differences on tokenizers between EleutherAI/gpt-neox-20b and kuotient/mamba-ko-2.8b are that kuotient/mamba-ko-2.8 added a special token '[PAD]' ("id": 50277) and its tokenizer model settings were different in only one place against EleutherAI/gpt-neox-20b: "byte_fallback": false. So I guess the tokenizer model in ```example_mamba_llm.py``` for my linux machine is just okay for both EleutherAI/gpt-neox-20b and kuotient/mamba-ko-2.8.

And on my Mac Studio with MLX, korean prompt made an broken result too. I changed tokenizer model as EleutherAI/gpt-neox-20b and tried again, it was still broken. The environment variable LC_CTYPE is set as UTF-8, so if the character codes printed by generate.py fit in UTF-8, terminal will render the codes into readable character images instead of printing question marks.

```
(venv_mamba_py) ******@Mac-Studio-2022-01 scripts % python generate.py --prompt="내가 살던 고향은" --hf_model_name="kuotient/mamba-ko-2.8b" --n_tokens=100

��가 ������ ������은 ������고 ������한 ���이����니다. �������� ����� ���, ���을 ��고 �������� �����로 ���어서�� �������니다. ��� ��� ��는 �����한 ���������� �%                                                                                                                                                       (venv_mamba_py) ******@Mac-Studio-2022-01 scripts % 
```

**Comment by alxndrTL** [comment]
That's very weird that the tokenizers behave differently from your linux machine to your Mac ... interesting..
We don't know if MLX has something to do with it... probably not
Maybe, if we want to be sure that the tokenizer is atfault here, you can check the differences between the tokenizer in linux and Mac :

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('EleutherAI/gpt-neox-20b')

tokenizer.encode(some_string)
```

with some korean string, and see if the token ids are the same..

If they are the same, you can try passing the same prompt through the model (torch and MLX) and compare the output token ids (with setting `sample=False` to get the same results).

**Comment by beebopkim** [comment]
I tinkered ```mamba_lm_mlx.py``` to get generated token IDs before decoding, acquired an token ID array from Apple Silicon, put into my Linux machine, and tried to decode with the tokenizer. It produced a flawless korean string, huh???

I investigated ```generate``` functions in ```mamba_lm_mlx.py``` and ```mamba_lm.py```, and found that the ```generate``` function in ```mamba_lm_mlx.py``` uses ```yield```, the generator in Python.

So, I removed the generator in the ```generate``` function, amended ```generate.py``` and the final results is this:

```
(venv_mamba_py) ******@Mac-Studio-2022-01 scripts % python generate.py --prompt="내가 살던 고향은" --hf_model_name="kuotient/mamba-ko-2.8b" --n_tokens=100
내가 살던 고향은 세상에서 가장 아름다운 곳이었습니다. 그것은 맑은 물, 푸른 하늘, 그리고 숨이 멎을 만큼 아름다운 산과 숲으로 가득 차 있었습니다.
(venv_mamba_py) ******@Mac-Studio-2022-01 scripts %
```

It looks like that the ```tokenizer.decode``` produces characters byte by byte, but when used by the Python generator, it seems to be unable to handle multibyte UTF-8 characters like korean, japanese, chinese, thai, cambodian, hindi, and etc.  Those characters are rendered in 3 byte length in UTF-8.

**Comment by alxndrTL** [comment]
Oh, ok, it makes sense now.
I used the python generator `yield` just like in the MLX docs ([inference training example](https://ml-explore.github.io/mlx/build/html/examples/llama-inference.html#generation)) to have a script that streams tokens instead of printing them all at once at the end.
