### ISSUE TITLE
Shape issue between get_batch() output and mamba.py forward() function

### ISSUE THREAD

**Issue by peterphancong** [alxndrTL/mamba.py#62]
Thank you for your implementation, it is very useful for me
However, I got an issue when I apply on data.
`def get_batch(data, seq_len, idx):`
 `      src = data[:, idx:idx+seq_len]` # only 2 over here
`        target = data[:, idx+1:idx+seq_len+1]`
`        return src, target`
then 
`input, output = get_batch(train_data, seq_length, idx)`
but in the mamba model, the forward function like this
`def forward(self, x):`
`        # x : (B, L, D)`
`        # y : (B, L, D)`
`        print(x.shape)`
`        _, L, _ = x.shape` # but 3 over here
`        xz = self.in_proj(x) # (B, L, 2*ED)`
.....`

They are different shape, so I got the error:

` _, L, _ = x.shape : ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by alxndrTL** [comment]
Hello,
yes, the Mamba model is not a LM model and thus dont have an embedding. Either you should use a MambaLM (which sticks a word embedding to a Mamba model) or use a word embedding yourself.
The batch function will give you (B, L) and when you pass that through the word embedding you will get the (B, L, D).
((B,L) is B sequences of tokens while (B, L, D) is B sequences of vectors, each vector representing a token)

Sorry for the late response.
