### ISSUE TITLE
Mamba from_pretrained example doesn't work

### ISSUE THREAD

**Issue by andrewwarrington** [alxndrTL/mamba.py#63]
Hi there,

I'm trying to reproduce the mamba `from_pretrained` from the example in the README.md, and I get the following error.  

```
>>> from mambapy.lm import from_pretrained
>>> model = from_pretrained('state-spaces/mamba-130m').to("cuda")
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 1.66MB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/mambapy/lm.py", line 289, in from_pretrained
    config = MambaConfig(d_model=config_data['d_model'], n_layers=config_data['n_layers'])
KeyError: 'n_layers'
```

Please advise :) 

Thanks,
A

**Comment by alxndrTL** [comment]
Hello,
Yes indeed it should be `n_layer` and not `n_layers`. I made the fix (you can easily modify the `n_layers` to `n_layer` also)
Sorry about that, that is weird as this code was tested.. Idk what happened (it's been a few months since I tested it tbf)

**Comment by andrewwarrington** [comment]
Thank you! :)
